#!/usr/bin/env node
// doc-tree.mjs — the documentation tree (KIT-T284). Docs mirror the code tree: every crate
// and concern folder carries a short header doc (README.md: what it is, where to go next),
// the trunk README is a map that points down, and docs/TREE.md is GENERATED from the units.
// A repo "has adopted" the tree once docs/TREE.md exists; the pre-write, commit and orient
// hooks key off that.
//
//   node scripts/doc-tree.mjs index [--write] [root]   print / write docs/TREE.md
//   node scripts/doc-tree.mjs lint [root]              findings; exit 1 when any
//   node scripts/doc-tree.mjs map [root]               trunk map (units one level down)
//
// Units: the repo root, every manifest dir (crate/package), and every directory directly
// holding source whose parent is a unit (or a unit's src/ or lib/) — a concern folder.

import { existsSync, readFileSync, writeFileSync, mkdirSync } from 'node:fs';
import { join, dirname, resolve, posix } from 'node:path';
import { fileURLToPath } from 'node:url';
import { walkTree, isSource, MANIFESTS } from './tree-walk.mjs';

export const HEADER = 'README.md';
export const INDEX_REL = 'docs/TREE.md';
export const TRUNK_MAX_LINES = 80;
export const HEADER_MAX_LINES = 60;
const PURPOSE_MAX = 140;
const ALWAYS_ROOTS = new Set(['CLAUDE.md', 'AGENTS.md', 'README.md', 'CHANGELOG.md', 'CONTRIBUTING.md', 'SECURITY.md']);
const NON_CONCERN = new Set(['tests', 'test', 'benches', 'examples', '__tests__', 'fixtures']);
const LICENSE_DOC = /^(LICENSE|COPYING|NOTICE)/i;

const parentOf = (rel) => (rel.includes('/') ? rel.slice(0, rel.lastIndexOf('/')) : '');
const baseOf = (rel) => rel.slice(rel.lastIndexOf('/') + 1);
const join2 = (rel, name) => (rel ? `${rel}/${name}` : name);

const hasManifest = (tree, rel) => !!tree.get(rel) && tree.get(rel).files.some((f) => MANIFESTS.has(f));
const isUnitRoot = (tree, rel) => rel === '' || hasManifest(tree, rel);
const hasAnySource = (tree) => [...tree.values()].some((e) => e.files.some(isSource));

/** 'root' | 'crate' | 'concern' | null for the directory `rel` of a walked tree. */
export function unitKind(tree, rel) {
  const entry = tree.get(rel);
  if (!entry) return null;
  if (rel === '') return hasAnySource(tree) || hasManifest(tree, '') ? 'root' : null;
  if (hasManifest(tree, rel)) return 'crate';
  if (!entry.files.some(isSource)) return null;
  const parent = parentOf(rel);
  const base = baseOf(rel);
  if (NON_CONCERN.has(base)) return null;
  if (isUnitRoot(tree, parent)) return base === 'src' || base === 'lib' ? null : 'concern';
  const grand = parentOf(parent);
  if ((baseOf(parent) === 'src' || baseOf(parent) === 'lib') && isUnitRoot(tree, grand)) return 'concern';
  return null;
}

/** Every unit as { dir, kind }, sorted by dir. */
export function findUnits(root, tree = walkTree(root)) {
  const units = [];
  for (const rel of tree.keys()) {
    const kind = unitKind(tree, rel);
    if (kind) units.push({ dir: rel, kind });
  }
  return units.sort((a, b) => a.dir.localeCompare(b.dir));
}

/** One-line purpose of a header doc: first prose line, else the first heading. */
export function purposeOf(text) {
  let heading = '';
  let inFence = false;
  for (const raw of text.split('\n')) {
    const t = raw.trim();
    if (t.startsWith('```')) { inFence = !inFence; continue; }
    if (inFence || !t || t.startsWith('<!--') || t.startsWith('[![') || /^[-=*_]{3,}$/.test(t)) continue;
    if (t.startsWith('#')) { heading ||= t.replace(/^#+\s*/, ''); continue; }
    if (/^(?:[-*>]|\d+\.)\s/.test(t) || t.startsWith('|')) continue;
    return clean(t);
  }
  return clean(heading);
}
const clean = (s) => s.replace(/\[([^\]]*)\]\([^)]*\)/g, '$1').replace(/[`*_]/g, '').trim().slice(0, PURPOSE_MAX);

const readHeader = (root, dir) => {
  const p = join(root, dir, HEADER);
  return existsSync(p) ? readFileSync(p, 'utf8') : null;
};

function nest(units) {
  const rows = units.map((u) => ({ ...u, depth: 0 }));
  for (const r of rows) {
    r.depth = rows.filter((o) => o !== r && (o.dir === '' || r.dir.startsWith(o.dir + '/')) && o.dir !== r.dir).length;
  }
  return rows;
}

/** The generated index text (docs/TREE.md) for `root`. */
export function buildIndex(root, tree = walkTree(root)) {
  const rows = nest(findUnits(root, tree));
  const out = [
    '# Doc tree',
    '',
    'Generated by `node scripts/doc-tree.mjs index --write` — do not edit. One entry per crate or',
    'concern folder; read the trunk, then descend only the branch you need.',
    '',
  ];
  for (const r of rows) {
    const text = readHeader(root, r.dir);
    const name = r.dir || '.';
    const pad = '  '.repeat(r.depth);
    if (text === null) { out.push(`${pad}- \`${name}\` — (no header doc)`); continue; }
    const link = posix.relative(posix.dirname(INDEX_REL), join2(r.dir, HEADER));
    out.push(`${pad}- [${name}](${link}) — ${purposeOf(text) || '(no purpose line)'}`);
  }
  return out.join('\n') + '\n';
}

/** Trunk map: the index entries one level below the root, for SessionStart. */
export function trunkMap(root) {
  const tree = walkTree(root);
  return nest(findUnits(root, tree)).filter((r) => r.depth <= 1).map((r) => {
    const text = readHeader(root, r.dir);
    return `${'  '.repeat(r.depth)}${r.dir || '.'} — ${text === null ? '(no header doc)' : purposeOf(text) || '(no purpose line)'}`;
  });
}

const mdLinks = (text) => [...text.matchAll(/\]\(([^)\s#]+)(?:#[^)]*)?\)/g)].map((m) => m[1]).filter((t) => !/^(?:[a-z]+:|\/\/)/i.test(t));
const titleOf = (text) => ((text.match(/^#\s+(.+)$/m) || [, ''])[1]).trim().toLowerCase();

/** Findings [{ rule, path, msg }] for the doc tree of `root`. */
export function lintDocTree(root) {
  const tree = walkTree(root);
  const units = findUnits(root, tree);
  const found = [];
  const headers = new Set();
  const purposes = new Map();
  for (const u of units) {
    const text = readHeader(root, u.dir);
    const path = join2(u.dir, HEADER);
    if (text === null) { found.push({ rule: 'missing-header', path: u.dir || '.', msg: `${u.kind} has no ${HEADER}` }); continue; }
    headers.add(path);
    const cap = u.kind === 'root' ? TRUNK_MAX_LINES : HEADER_MAX_LINES;
    const lines = text.split('\n').length;
    if (lines > cap) found.push({ rule: 'header-too-long', path, msg: `${lines} lines exceeds the ${cap}-line cap for a ${u.kind} header — push detail down a level` });
    const purpose = purposeOf(text);
    if (!purpose) { found.push({ rule: 'header-no-purpose', path, msg: 'no purpose line' }); continue; }
    const key = purpose.toLowerCase();
    if (purposes.has(key)) found.push({ rule: 'duplicate-doc', path, msg: `same purpose line as ${purposes.get(key)}` });
    else purposes.set(key, path);
  }
  const mds = [];
  for (const [dir, e] of tree) for (const f of e.files) if (f.endsWith('.md') && !LICENSE_DOC.test(f)) mds.push(join2(dir, f));
  const mdSet = new Set(mds);
  const seeds = [...headers, INDEX_REL, ...mds.filter((p) => ALWAYS_ROOTS.has(p))].filter((p) => mdSet.has(p));
  const reached = new Set(seeds);
  const queue = [...seeds];
  while (queue.length) {
    const cur = queue.pop();
    let text;
    try { text = readFileSync(join(root, cur), 'utf8'); } catch { continue; }
    for (const link of mdLinks(text)) {
      const target = posix.normalize(join2(parentOf(cur), link));
      if (mdSet.has(target) && !reached.has(target)) { reached.add(target); queue.push(target); }
    }
  }
  const titles = new Map();
  for (const p of mds) {
    if (headers.has(p) || p === INDEX_REL) continue;
    if (!reached.has(p)) found.push({ rule: 'orphan-doc', path: p, msg: 'not reachable from the doc tree (link it from a header doc or the index)' });
    const t = titleOf(readFileSync(join(root, p), 'utf8'));
    if (t && titles.has(t)) found.push({ rule: 'duplicate-doc', path: p, msg: `same title as ${titles.get(t)}` });
    else if (t) titles.set(t, p);
  }
  const indexPath = join(root, INDEX_REL);
  if (!existsSync(indexPath)) found.push({ rule: 'missing-index', path: INDEX_REL, msg: 'run: node scripts/doc-tree.mjs index --write' });
  else if (readFileSync(indexPath, 'utf8') !== buildIndex(root, tree)) {
    found.push({ rule: 'stale-index', path: INDEX_REL, msg: 'out of date — run: node scripts/doc-tree.mjs index --write' });
  }
  return found;
}

/** True once `root` has adopted the doc tree (the generated index exists). */
export const adoptedDocTree = (root) => existsSync(join(root, INDEX_REL));

function main(argv) {
  const [cmd, ...rest] = argv;
  const write = rest.includes('--write');
  const root = resolve(rest.find((a) => !a.startsWith('--')) || process.cwd());
  if (cmd === 'index') {
    const text = buildIndex(root);
    if (!write) { process.stdout.write(text); return 0; }
    mkdirSync(dirname(join(root, INDEX_REL)), { recursive: true });
    writeFileSync(join(root, INDEX_REL), text);
    process.stdout.write(`wrote ${INDEX_REL}\n`);
    return 0;
  }
  if (cmd === 'lint') {
    const found = lintDocTree(root);
    for (const f of found) process.stdout.write(`${f.rule}  ${f.path}  ${f.msg}\n`);
    process.stdout.write(found.length ? `${found.length} finding(s)\n` : 'doc tree clean\n');
    return found.length ? 1 : 0;
  }
  if (cmd === 'map') { process.stdout.write(trunkMap(root).join('\n') + '\n'); return 0; }
  process.stderr.write('usage: doc-tree.mjs <index [--write] | lint | map> [root]\n');
  return 2;
}

if (process.argv[1] && resolve(process.argv[1]) === fileURLToPath(import.meta.url)) process.exit(main(process.argv.slice(2)));
